### ISSUE TITLE
The file upload action cannot be canceled

### ISSUE THREAD

**Issue by handsome-hao** [jamf/JamfSync#15]
https://github.com/jamf/JamfSync/assets/52556030/985a3815-e719-4bed-9071-edc3fc727e33

\(^_^)Do you have such a problem? Jamf Sync won't let me cancel the upload？(。・_・。)(。・_・。)

**Comment by HarryStrandJamf** [comment]
Hmm...strange. I know there is an issue when copying files locally where it won't cancel in the middle of copying a file, and that is a tough one since Swift's FileManager doesn't handle that, but I see you're synchronizing to a JCDS DP. I tried to replicate this with 1.3.0 and wasn't able to. I'll watch for it though.

**Comment by macserv** [comment]
Seeing the same issue here, JCDS as well.
Jamf Sync 1.3.2, Jamf Pro Cloud 11.6.0

**Comment by macserv** [comment]
Addendum to above:  While I can't cancel, I can **_close_** the "Transfer Progress" window, which is kind of confusing.

I can also quit the app, which warns me about a sync in progress and then crashes on exit.  Crash report (redacted) attached.

[Crash-Jamf_Sync-20240705104702.txt](https://github.com/user-attachments/files/16111134/Crash-Jamf_Sync-20240705104702.txt)

**Comment by HarryStrandJamf** [comment]
Fixed in version 1.3.3. I wasn't able to recreate the crash when exiting, but hopefully you won't be able to recreate it with version 1.3.3 either.
