### ISSUE TITLE
Jamf Sync remove the package from source location

### ISSUE THREAD

**Issue by MehdiYawari** [jamf/JamfSync#22]
While testing the Jamf Sync, I realised that once I choose a package and click on synchronize. The package is removed from source location. I thought that synchronisation will copy the selected package to destination location.
i tested this behaviour multiple times and everytime it occurs.
The Worst Part is, that sometime the synchronisation fails the source packages are also deleted

**Comment by HarryStrandJamf** [comment]
Hmm...that's not good. What type of distribution point was the source and which type was the destination?

**Comment by MehdiYawari** [comment]
Yes I used the latest version available: 1.3.2
Source: a local folder on macOS
Destination: File share distribution points --> SMB Share which we used Jamf admin to connect to and upload packages

**Comment by HarryStrandJamf** [comment]
I'm not seeing that behavior. It does redraw the source list, and if it's sorting by the Sync status, which seems to be the default, it will move the item because the status will change to a circle with an '=' instead of a circle with a '+'. Is that perhaps what's happening? Otherwise, if you click the refresh button (to the left of "Show Log"), does the file come back? If you look at that directory in Finder, does the file disappear there as well? If there still seems to be an issue with this, could you send me a screen shot of a finder view before and after showing the missing file and click "Show Log", select any relevant items and click the copy button and send that as well? A screen shot of the main window with the source and destination selected would also be helpful.

**Comment by HarryStrandJamf** [comment]
I'm going to mark this as not planned since I wasn't able to recreate it and I haven't received more information. If I get more information, we can reopen it.
