### ISSUE TITLE
Password not saved in keychain for local dp account

### ISSUE THREAD

**Issue by david-london** [jamf/JamfSync#23]
I tick the check box to save the password in my keychain for the local SMB Distribution Point but it doesn't save but gets used for the session.  It has saved for my cloud DP - just not the local DP.  Is there some trick to this?

**Comment by HarryStrandJamf** [comment]
This should be working and I'm not sure why it wouldn't work. You can go into the **Keychain Access** app and type "JamfSync" in the search bar and it will show you all of the keychain entries that are saved. The ones for distribution points end with ".dp". If you double click on these, you can get details about what's in it. These contain the user name. If you switch between a couple different user names for that distribution point, I would assume that last one used would probably be saved, so the next time if you use a different user id, it probably wouldn't able to find the password for that. Do you think this may be happening to you?

**Comment by david-london** [comment]
@HarryStrandJamf - Thank you and sorry.  I should have looked in the keychain.  It's working now.  

Thank you for all your work on this project.  It's a pretty hard thing doing a project like this and I really wish Jamf would support it.  We are about 3300km from the Jamf Cloud DP and need a local DP when deploying to machines on site.

**Comment by david-london** [comment]
Resolved

**Comment by HarryStrandJamf** [comment]
Thanks! I appreciate your appreciation! I'm glad that worked for you! I understand your concern about the lack of support, but I and BIG_RAT try to support it as we have time. The hope is that other people in the community will step in to help with bug fixes and new features since it's open source, but we'll see if that happens. Version 1.3.3 is almost ready to release, and that will solve several issues.
