### ISSUE TITLE
Cloud Distribution Point not available unless set as primary

### ISSUE THREAD

**Issue by robertgendler** [jamf/JamfSync#26]
Jamf Admin allowed us to upload packages to our own AWS S3 bucket. Jamf Sync does not even show this as being available.

Cloud Distribution Points **MUST** be marked as the primary distribution source for Jamf Sync to see it and work. 

Please add the ability to use Jamf Sync and Cloud Distribution Points when they are not marked as the primary source.

**Comment by clarkep20** [comment]
I need this feature to work as well. What a tremendous oversight. I can't imagine a school that would want everything going out to the cloud for everything, this would crush our network.

**Comment by jamfadmin274** [comment]
I also am setting up Jamf Sync and even after connecting my JAMF Pro server using the API client it does not pull in my cloud distribution point. I am thinking this is a bug.

**Comment by HarryStrandJamf** [comment]
The interface that Jamf Admin used was not secure enough, which was why it had to go. The Jamf Pro server folks added an API call for uploading packages to the primary distribution point since it was needed for the UI. If they were to add an interface to upload to any cloud distribution point, I would be happy to make a change to use that. You may want to suggest a feature request for updating the API to do allow for uploading to non-primary cloud distribution points. Alternatively, if anyone with programming skills would like to add the ability to synchronize to an S3, Rackspace, or Akamai distribution point, I would be happy to provide information on the best way to do that. But for now I'm going to close this as not planned.
