### ISSUE TITLE
Jamf Sync has 'No-Entry' symbol on icon in macOS Ventura 13.x

### ISSUE THREAD

**Issue by pvillave** [jamf/JamfSync#30]
Cannot use Jamf Sync on macOS Ventura 13.x....
What is the problem with macOS 13.x Ventura for Jamf Sync??????????????????
?????????????????????????????????????????????????????????????????????????
?????????????????????????????????????????????????????????????????????????
?????????????????????????????????????????????????????????????????????????
?????????????????????????????????????????????????????????????????????????
?????????????????????????????????????????????????????????????????????????
?????????????????????????????????????????????????????????????????????????

Deprecated Jamf Remote...fantastic tool
Deprecated Jamf Admin... fantastic working tool
Now have broken Jamf Sync...is this a continuing pattern ?

**Comment by HarryStrandJamf** [comment]
Jamf Sync was written from scratch, which meant we could use the latest and greatest from Apple, which not only made development easier but also ensured that it would last far into the future with minimal maintenance. But in order to do this, we had to make macOS 14.0 as the oldest version of macOS that is supported. I realize it's not ideal for people with older macs, since you will need to upgrade in order to use the tool, but it was more practical to focus our efforts on the future instead of supporting older versions of macOS.

**Comment by pvillave** [comment]
Interesting as Jamf has always made the software tools work on any version of macOS almost no matter of which version of the tools you wanted/needed to use.  For a while, Jamf Admin had to be the same version as the jamf binary, but that didn't last forever.  It got quite robust in all this, then the Deprecating began...& now we're down to just Composer...last of the Great Tools!
