### ISSUE TITLE
Zip files greyed out for upload

### ISSUE THREAD

**Issue by MisterE-gh** [jamf/JamfSync#33]
Files with the zip extension are not recognized for upload 
On the most recent version of the app 1.3.2, the local source listing does not show any zip files.  Also, upon clicking on the plus button to upload to an SMB share, all zip files are greyed out, and cannot be clicked

examples are VSCode-darwin-universal.zip, and JamfSync.app.zip in a local downloads folder

**Comment by HarryStrandJamf** [comment]
So currently it only recognizes zip files ending in ".pkg.zip" or ".mpkg.zip". The reason for this is because it only allows you to upload files that can be used in a Jamf Pro policy. Not planning to change this so I'm closing it as Not Planned, but if you can come up with a use case where this is needed, let me know.
