### ISSUE TITLE
Not able to upload huge files like 14GB.

### ISSUE THREAD

**Issue by sashankpeddi1** [jamf/JamfSync#4]
We tried uploading a huge file using JAMF Sync, irrespective to the location and network we use it is getting failed, while it creating a record in DB.
![sync](https://github.com/jamf/JamfSync/assets/106247145/d803dba2-a51f-4723-80bf-23c9807b2eef)

**Comment by HarryStrandJamf** [comment]
With version 1.3.0, I was able to make a change to give more info about why an upload failed, and that indicated that it was failing because the file was over 5 GB (that's the one with the response code of 400). It turns out that that is the size limit for how Jamf Sync is uploading and there should be a different way to handle that. Hopefully we can get that done for the version after 1.3.0 🤞 . In the meantime, for those files, you may want to upload them directly using Jamf Pro.

**Comment by joshnovotny** [comment]
Have all my packages synced except one at 14GB, and cannot upload manually since JCDS is not my primary, so hoping this gets fixed soon.

**Comment by killer23d** [comment]
Since Jamf Admin doesn't work properly with Jamf Cloud, and Jamf Sync cannot upload more than 5GB. I really need to have this resolved so I can sync my packages to JCDS.

**Comment by HarryStrandJamf** [comment]
@killer23d, is the JCDS marked as your primary distribution point? If so, you should be able to upload larger files via the Jamf Pro UI in Settings / Packages, as a workaround. I'm planning to create a minor update to Jamf Sync fairly soon, and I'm not sure if I'll be able to get this fixed before then.

**Comment by killer23d** [comment]
> @killer23d, is the JCDS marked as your primary distribution point? If so, you should be able to upload larger files via the Jamf Pro UI in Settings / Packages, as a workaround. I'm planning to create a minor update to Jamf Sync fairly soon, and I'm not sure if I'll be able to get this fixed before then.

The issue with Jamf Admin is that it keeps re-syncing newly created 5GB packages repeatedly to Jamf Cloud, other DPs are OK. We are on hybrid and due to bandwidth limitations we can't change JCDS as primary at this point. Right now the process for me to upload is:

- Use Jamf Admin to upload to on-prem primary DP, sync to Jamf Cloud once.
- Use Jamf Sync to sync to JCDS again and do checksum

It is quite an annoyance but I will live with it for now. Take your time. Since I can't automate Jamf Sync like Jamf Admin, I am replicating my 100 DPs with Rsync and Robocopy.

**Comment by HarryStrandJamf** [comment]
Thanks for the info @grahampugh! The code in Jamf Sync currently doesn't use the AWS Swift package, and I am planning to try to incorporate that as soon as I'm able to find time to work on it. I appreciate the info! That should be a nice guide!

**Comment by HarryStrandJamf** [comment]
Implemented in version 1.3.3.
