### ISSUE TITLE
macOS 14 only?

### ISSUE THREAD

**Issue by magnusviri** [jamf/JamfSync#5]
I'm on macOS 13. Are you making this available for macOS 13?

```
/Users/james/Downloads/Jamf\ Sync.app/Contents/MacOS/Jamf\ Sync 
dyld[70512]: Symbol not found: _$s7SwiftUI32AlternatingRowBackgroundBehaviorV8disabledACvgZ
  Referenced from: <0B234B1D-5638-3EB8-A6BD-E5DFE3B76756> /Users/james/Downloads/Jamf Sync.app/Contents/MacOS/Jamf Sync (built for macOS 14.0 which is newer than running OS)
  Expected in:     <DB523CD7-7709-3E27-B8C4-D89B0383AEAE> /System/Library/Frameworks/SwiftUI.framework/Versions/A/SwiftUI
zsh: abort      /Users/james/Downloads/Jamf\ Sync.app/Contents/MacOS/Jamf\ Sync
```

**Comment by HarryStrandJamf** [comment]
Since JamfSync was built from the ground up, we wanted to use the latest available technology from Apple. This not only makes the program better, but it also means it will take longer before the technology in use today will be deprecated in the future, which means less maintenance will be needed. So no, we're not planning to support < 14.0. I understand that moving to a newer platform can be difficult, but that is your best path forward if you need to use Jamf Sync.

**Comment by magnusviri** [comment]
If I understand correctly, this is the replacement for Jamf Admin, which is going to quit working fairly soon. Is that the case?

**Comment by HarryStrandJamf** [comment]
I wouldn't call it a direct replacement, but rather a tool that can be used to help replace some of the workflows that Jamf Admin provided. Yes, Jamf Admin will be discontinued as of Jamf Pro 11.6.
