### ISSUE TITLE
No "Settings..." menu item under the App menu?

### ISSUE THREAD

**Issue by magnusviri** [jamf/JamfSync#9]
There's no "Settings..." menu item under the App menu. I don't know if you're following the HIG, but it still says to include a Settings menu item there. Please make sure the keyboard shortcut is command-comma, which is pretty universal across all apps on macOS.

https://developer.apple.com/design/human-interface-guidelines/the-menu-bar

![Screenshot 2024-05-28 at 10 41 04 AM](https://github.com/jamf/JamfSync/assets/711269/82a61235-2107-49b3-8b2d-e99ce7c37741)

**Comment by HarryStrandJamf** [comment]
I had planned to add the Setup menu under there, however, since processing needs to happen when things are changed, it was not very straightforward how to make this happen and time was very limited. Technically that isn't user preferences either, which would typically be under "Settings...", and Jamf Sync doesn't yet have any user preference settings but may in the future. Still may do this at some point, but it's kind of on the back burner for now.

**Comment by HarryStrandJamf** [comment]
I'm going to close this as not planned. Technically the Setup menu really isn't the same thing as Settings. Setup is used to set up all of the Jamf Pro instances and local file folders. Settings is generally used for preferences. I may add a settings menu at some point when I need to add preferences that don't really fit with Setup.

**Comment by HarryStrandJamf** [comment]
There is a settings menu as of 1.4.0 now. It just has global preferences though, and is not the same as Setup.
